### ISSUE TITLE
AbstractDBTest fails if there is no *.sql file.

### ISSUE THREAD

**Issue by amorfis** [softwaremill/softwaremill-common#1]
Next to TestDBTest, there is an TestDBTest.sql file. If this file is removed, test fails.

If I don't need to populate DB with test data it would be nice if I didn't need to provide .sql file.

**Comment by softwaremill** [comment]
I agree the test should be clever enough, but a s a workaround You can override protected void loadTestData(EntityManager em) with an empty method

**Comment by adamw** [comment]
Implemented by amorfis
